name: "ft_110M_en_hi"

# use `init_from_nemo_model` or `init_from_pretrained_model` to initialize the model
# We do not currently support `init_from_ptl_ckpt` to create a single script for all types of models.
# init_from_pretrained_model: ${oc.env:pretrain_module} # path to nemo model
# init_from_nemo_model: null # path to nemo model

# init_from_nemo_model: ${oc.env:nemo_model} # path to nemo model

model:
  sample_rate: 16000
  compute_eval_loss: false # eval samples can be very long and exhaust memory. Disable computation of transducer loss during validation/testing with this flag.
  log_prediction: true # enables logging sample predictions in the output during training
  rnnt_reduction: "mean_volume"
  skip_nan_grad: true
  # use_cer: true
  # ckpt_path: ${oc.env:ckpt_path}


  train_ds:
    use_lhotse: True
    tarred_audio_filepaths: null
    input_cfg:
      - type: nemo
        manifest_filepath: train_hi.json
        weight: 0.7
        tags:
          lang: hi
      - type: nemo
        manifest_filepath: train_en.json
        weight: 0.3
        tags:
          lang: en

    sample_rate: ${model.sample_rate}
    batch_size: null # you may increase batch_size if your memory allows
    shuffle: true
    num_workers: 4 #
    pin_memory: false
    max_duration: 30.0 #16.0
    min_duration: 1.0
    # tarred datasets
    is_tarred: false
    shuffle_n: 2048
    # bucketing params
    bucketing_strategy: "fully_randomized"
    use_bucketing: True
    num_buckets: 30
    bucket_duration_bins: null
    batch_duration: 600 # 800s for 8 bit optim
    quadratic_duration: 15
    bucket_buffer_size: 20000
    shuffle_buffer_size: 10000
    # pretokenize: false
    # augmentor:
    #   white_noise:
    #     prob: 0.5
    #     min_level: -50
    #     max_level: -10
    #   impulse:
    #     prob: 0.3
    #     manifest_path: ${oc.env:manifest_noise_argument}

  validation_ds:
    ds_item:
      # - name: dataset_en
      #   manifest_filepath: /ws/dataset/ASR/data/dev_clean_2.json
      #   sample_rate: ${model.sample_rate}
      #   batch_size: 8
      #   shuffle: false
      #   use_start_end_token: false
      #   num_workers: 4
      #   pin_memory: false
      #   use_bucketing: false
      - name: dataset_hi
        manifest_filepath: val_hi.json
        sample_rate: ${model.sample_rate}
        batch_size: 8
        shuffle: false
        use_start_end_token: false
        num_workers: 4
        pin_memory: false
        use_bucketing: false

  # test_ds:
  #   manifest_filepath: null
  #   sample_rate: ${model.sample_rate}
  #   batch_size: 1
  #   shuffle: false
  #   use_start_end_token: false
  #   num_workers: 8
  #   pin_memory: true

  char_labels: # use for char based models
    update_labels: false
    labels: null # example list config: \[' ', 'a', 'b', 'c'\]

  tokenizer: # use for spe/bpe based tokenizer models
    update_tokenizer: true
    dir: en1024_hi256 # path to directory which contains either tokenizer.model (bpe) or vocab.txt (for wpe)
    type: bpe # Can be either bpe (SentencePiece tokenizer) or wpe (WordPiece tokenizer)

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    # Cutout parameters
    rect_masks: 5 # Number of rectangles to cut from any given spectrogram
    rect_freq: 50 # Max cut of size 50 along the frequency dimension
    rect_time: 120 # Max cut of size 120 along the time dimension
    # SpecAugment parameters
    freq_masks: 2 # set to zero to disable it
    freq_width: 15
    time_masks: 10 # set to zero to disable it
    time_width: 25

  optim:
    name: adamw # adamw8bit
    lr: 1e-4 
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 1e-4

    # scheduler setup
    sched:
      name: CosineAnnealing
      # d_model: 512
      # monitor: val_loss
      # scheduler config override
      warmup_steps: 5000
      warmup_ratio: null
      min_lr: 1e-6 #5e-6
      max_steps: 100000
  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    fuse_loss_wer: true
    fused_batch_size: 4

  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null
    random_state_sampling: false
    blank_as_pad: true
    prednet:
      pred_hidden: 640
      pred_rnn_layers: 1
      t_max: null
      dropout: 0.2
    vocab_size: 2021 #1521
    bnb_optim: true

  decoding:
    strategy: "greedy_batch" # can be greedy, greedy_batch, beam, tsd, alsd.

    # greedy strategy config
    greedy:
      max_symbols: 10

    # beam strategy config
    beam:
      beam_size: 2
      return_best_hypothesis: False
      score_norm: true
      tsd_max_sym_exp: 50 # for Time Synchronous Decoding
      alsd_max_target_len: 2.0 # for Alignment-Length Synchronous Decoding

    # The section which would contain the decoder and decoding configs of the auxiliary CTC decoder
  aux_ctc:
    ctc_loss_weight: 0.3 # the weight used to combine the CTC loss with the RNNT loss
    use_cer: true
    use_cr_ctc: True
    ctc_reduction: "mean_volume"
    decoder:
      _target_: nemo.collections.asr.modules.ConvASRDecoder
      feat_in: null
      num_classes: -1
      vocabulary: []
    decoding:
      strategy: "greedy_batch"

trainer:
  devices: [0] # number of GPUs, -1 would use all available GPUs
  num_nodes: 1
  max_epochs: -1
  max_steps: 500000 # computed at runtime if not set
  val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  accelerator: gpu
  # strategy:
  #   _target_: lightning.pytorch.strategies.DDPStrategy
  #   gradient_as_bucket_view: true
  accumulate_grad_batches: 2
  gradient_clip_val: 2.0
  precision: bf16 # Should be set to bf16-mixed/16-mixed for O1 and O2 to enable the AMP.
  log_every_n_steps: 100 # Interval of logging.
  enable_progress_bar: True
  num_sanity_val_steps: 2 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
  sync_batchnorm: true
  enable_checkpointing: False # Provided by exp_manager
  logger: false # Provided by exp_manager
  use_distributed_sampler: false # Lhotse has its own distributed sampler
  limit_val_batches: 20
  limit_train_batches: 10000
exp_manager:
  exp_dir: ./model_hi_test_110M
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    # in case of multiple validation sets, first one is used
    monitor: "val_wer"
    mode: "min"
    save_top_k: 3
    always_save_nemo: True # saves the checkpoints as nemo files along with PTL checkpoints
    # every_n_train_steps: 100
    every_n_epochs: 1
    dirpath: null #${oc.env:resume_from_dirpath}
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
  resume_from_checkpoint: null #${oc.env:resume_from_checkpoint}

  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
